Update uptime.yml

diff --git a/.github/workflows/uptime.yml b/.github/workflows/uptime.yml
--- a/.github/workflows/uptime.yml
+++ b/.github/workflows/uptime.yml
@@ -38,6 +38,13 @@ jobs:
         env:
           GH_PAT: ${{ secrets.GH_PAT || github.token }}
           SECRETS_CONTEXT: ${{ toJson(secrets) }}
+      # - name: Trigger Workflow in Private Repo
+      #   run: |
+      #     curl -X POST \
+      #       -H "Accept: application/vnd.github+json" \
+      #       -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_PAT }}" \
+      #       https://api.github.com/repos/teamfolia/test-automation/actions/workflows/loadProject.yml/dispatches \
+      #       -d '{"ref":"main"}'
       - name: Trigger Workflow in Private Repo
         run: |
           curl -X POST \
@@ -45,3 +52,12 @@ jobs:
             -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_PAT }}" \
             https://api.github.com/repos/teamfolia/test-automation/actions/workflows/loadProject.yml/dispatches \
             -d '{"ref":"main"}'
+
+      - name: Handle Trigger Response
+        run: |
+          if [ "${{ steps.trigger_workflow.outputs.status }}" == "success" ]; then
+            echo "Workflow was triggered successfully."
+          else
+            echo "Workflow trigger failed."
+            exit 1
+          fi
